name: Hardhat Tests

on:
  push:
  pull_request_target:

jobs:
  test:
    name: Run Hardhat Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile contracts
        run: pnpm hardhat compile

      - name: Run tests and report test coverage
        run: SOLIDITY_COVERAGE=true pnpm hardhat coverage

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
